name = "my-cloquetaro"
main = "dist/index.js"
compatibility_date = "2025-03-17"
compatibility_flags = ["nodejs_compat"]
account_id = "221617d49b0255edff33e5cd73b08eb5"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
#main = "src/index.ts"
#workers_dev = true
#minify = true

# [build]
# command = "pnpm run build"
# cwd = "."
# watch_dir = "src"


# 开发环境配置
[env.development]
name = "my-cloquetaro-dev"
vars = { NODE_ENV = "development" }

[env.production]
name = "my-cloquetaro-prod"
vars = { NODE_ENV = "production" }

# 如果需要绑定 KV 存储，取消下面的注释并修改名称
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"